ansible-collections/vmware_rest_code_generator

refresh_modules.py
test_refresh_modules.py

Prepare the final module with `.format()`, this instead of `astunparse`.
We still use `astunparse`, but on level above.

use format, instead of astunparse to reduce complexity

---

refresh_modules.py

Technically speaking, we should use `/usr/bin/python3`. But `ansible-test sanity` raise an error. So let's switch back to that for now.

use /usr/bin/python in the shebang

---

refresh_modules.py
test_refresh_modules.py

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/7
Do not build the modules when they depend on API with the Technology
Previous status:
- vcenter_vm_compute_policies_info
- vcenter_vm_console_tickets

ignore end-points with Tech Preview status

---

refresh_examples.py

Only include tasks with a name in the example.

examples: ensure tasks always come with a name

---

refresh_modules.py
test_refresh_modules.py

Simplify the code base and use a single source to know if a module
should be included.

use .is_trusted() to know if a module should be included

---

refresh_modules.py

Skip vcenter_vm_guest_power and vcenter_vm_guest_power_info because
we've already vcenter_vm_power and vcenter_vm_power_info.
Depends-On: https://github.com/ansible-collections/vmware_rest/pull/71

don't generate vcenter_vm_guest_power* modules

---

refresh_modules.py
test_refresh_modules.py

Now, what was in `vcenter_vm_hardware_ethernet_disconnect` is now part of
`vcenter_vm_hardware_ethernet`. The user can use `state: disconnect` to
trigger the end-point.
This is a more Ansibl-ish approach and this will reduce the number of modules.

avoid action module like foo_disconnect

---

refresh_modules.py

Add a workaround for the `upgrade_version` parameter of
`vcenter_vm_hardware`.

update: add a workaround for vm_hardware

---

module_utils/test_vmware_rest.py
module_utils/vmware_rest.py
refresh_modules.py
tox.ini

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/19
This way we can work with `cdrom`, not only `adapter`.
- identify subdevice from the url
- move some functions in module_utils.py

improve the way existing device are identified

---

refresh_modules.py
test_refresh_modules.py

Refactoring to reduce the complexity of the code base. There is two
different functions in charge of the transformation:
-  flatten_ref(): follow the $ref keys and return a data structure
- _property_to_parameter(): convert the properties to a list of
parameters, compatible with Ansible
- payload() now consumes flatten_ref() output.

simplify the properties transformation

---

refresh_modules.py

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/643
- loop on the operations in the same order all the time.
- always starts with "create" because the result looks better.

doc: improve the idempotency of the result

---

refresh_modules.py

Don't set the `elements` key when type is `dict`.

only set "elements" key for list

---

refresh_modules.py

These modules are broken. We don't build them anymore.
- vcenter_vm_tools_installer
- vcenter_vm_tools_installer_info
Disable the `upgrade` state of `vcenter_vm_tools`, which is broken too.

drop some vm_tools related modules

---

refresh_modules.py

Ensure the `state` field is either:
- required == True
- or comes with a default value.

ensure state field is required or default

---

module_utils/vmware_rest.py
refresh_modules.py

vcenter_rest_log_file: this optional parameter can be used to point on the
log file where all the HTTP interaction will be record.

vcenter_rest_log_file: add ability to record the HTTP interaction

---

refresh_modules.py

Ensure can pass a bare `ansible-test sanity` with Ansible 2.9 and 2.10.

sanity: extend the ignore files to cover 2.9

---

refresh_modules.py

Do show up the `I(state=['foo'])` for the list or get operationIds. It's
superfluous and source of confusion.
Also, ensure the entries from the `choices` list are not duplicated.
See: https://github.com/ansible-collections/vmware.vmware_rest/issues/123

doc: don't show required state for _info mod

---

module_utils/vmware_rest.py

`aiohttp.TCPConnector(limit=20, ssl=True)` was actually similar to
`aiohttp.TCPConnector(limit=20, ssl=False)`...

raise error if SSL check fails

---

refresh_modules.py

This commit breaks on Python3.6. This kind of situation should never
happens. I will adjust the CI to catch this kind of regression sooner
in the future.
This reverts commit 7ec27ed6e49238822674b34d812c442b3745874a.

Revert "use raw string for EXAMPLES and RETURN"

---

module_utils/vmware_rest.py

Properly handle `validate_certs` as a boolean and accepts all the
standard Ansible values (`yes`, `true`, `y`, `no`, etc).

ensure validate_certs is a boolean

---

vmware_rest_code_generator/cmd/refresh_modules.py

Adjust the shebang to avoid the validate-modules error.

address the missing-python-interpreter warning

---

vmware_rest_code_generator/cmd/refresh_modules.py

Do not call `flatten_ref()` to avoid a dependency at this level.
We already call `flatten_ref()` when necessary.

definitions.get: do not call flatten_ref()

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py

- associate the parameter with the operationId, instead of the state.
This is helpful to make the difference between `create` and `update`.
- turn on list parameter of `required_if` to be sure all the parameters
are not mandatory at the same time.

improve required_if generation

---

vmware_rest_code_generator/cmd/refresh_examples.py

Prefix the `ruamel.yaml` instance with a `_`` to be sure we don'þ
overwrite the `yaml` module.

refresh_examples: do not overwrite yaml module

---

vmware_rest_code_generator/cmd/refresh_modules.py

Ensure the target `module_utils` directory is present before we
write the module_utils file.

create target module_utils directory if missing

---

vmware_rest_code_generator/templates/default_module.j2

If the resource does not accept a get operation, we don't try to retrive
extra details.

create returns the full details only when possible

---

vmware_rest_code_generator/cmd/refresh_modules.py

We only support python 3.6 and greater.

sanity: skip import and test with py3.6 <

---

vmware_rest_code_generator/cmd/refresh_modules.py

This because of some long lines in the RETURNS section.

ignore pep8 for appliance_infraprofile_configs

---

README.md

Add Code of Conduct reference to README
- Docs Pull Request
README
Ansible managed collections have always been under the CoC, but let's be explicit

Add Code of Conduct reference to README

---

vmware_rest_code_generator/cmd/refresh_modules.py

Remove from the list:
- missing-main-call
- missing-if-name-main

ignore-2.12: remove some deprecated tests

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py

The documentation reports a wrong description for the `vcenter_password` parameter:
```yaml
vcenter_password: 
description:
- The vSphere vCenter username 
```
It should be
```yaml
vcenter_password: 
description:
- The vSphere vCenter password 
```
- Bugfix Pull Request

Attempt to fix documentation generation for vcenter_password

---

vmware_rest_code_generator/cmd/refresh_modules.py

with py3.10, get_event_loop() raises a deprecation warning. We will switch to asyncio.run()
when we will drop py3.6 support.
See: https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop

ignores-2.12: import-3.10!skip

---

vmware_rest_code_generator/cmd/refresh_modules.py

We cannot create a functional local account. The 7.0.2 API creates an
account without any UNIX groups.
In addition, only the first role of the list is actually  attached to
the new account.

disable appliance_localaccounts for now

---

vmware_rest_code_generator/module_utils/vmware_rest.py

- any retcode >= 400 is an error: For instance 403 should return a
module  failure.
- accept delete with 404

update_changed_flag: handle extra cases

---

vmware_rest_code_generator/module_utils/vmware_rest.py

We don't need this anymore and it's confusing for the users.

remove the _debug_info field from the result

---

vmware_rest_code_generator/api_specifications/7.0.2/content.json

The `/api/content/library/item` end-point expect a named argument. e.g:
`/api/content/library/item?library_id=foo`
If we keep the original string, we end-up with
`/api/content/library/item?library&library_id=foo` in the final module.

content.json: remove a unexpected parameter

---

vmware_rest_code_generator/templates/default_module.j2

When we do a patch and get a success (204) with no content, we now
do a final get call and return this output.

improve the output of patch and 204 with no content

---

commit_modules.sh

Simplify how we can ansible-test and pre-install all the requirements.

commit_modules: avoid a-test --requirements parameters

---

vmware_rest_code_generator/templates/default_module.j2

vcenter_vm_guest_customization was silently returning 400 or 500+
errors. The module was ignoring the error code and returning a success
message. This is not the case anymore.
Thanks Jerry Corum for reporting this.

PUT: raise an error in case of !300< err code

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py
vmware_rest_code_generator/config/modules.yaml

overwrite documentation of vcenter_vm_*power modules
Read the documentation from the config/modules.yaml configuration file.
See: https://github.com/ansible-collections/vmware.vmware_rest/issues/124

Overwrite documentation of vcenter vm  power modules

---

setup.cfg

This to avoid the following error:
error: can't copy 'config/modules.yaml': doesn't exist or not a regular file

setup.cfg: use a wildcare to import the conf file

---

vmware_rest_code_generator/module_utils/vmware_rest.py

Ensure we call open() with the encoding parameter.

pylint: call open() with encoding parameter

---

vmware_rest_code_generator/templates/default_module.j2

The end-point returns an exception but the configuration is actually
applied. We can get ride of the problem by doing a `yum update` on the
vCenter, but this is not supported officially by VMware.

workaround for appliance_networking_dns_servers

---

vmware_rest_code_generator/module_utils/vmware_rest.py

Properly return the subdevice if the URL comes with a {...} pattern.

subdevice and {} in URL

---

test-requirements.txt

We don't need to depend on the full ansible distribution for the tests.

tests: depends on ansible-core, not ansible

---

vmware_rest_code_generator/module_utils/vmware_rest.py

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1236
Problem identified with:
```
vcenter_datacenter:
name: foo
state: absent
```
If `foo` does not exist, we get a 404 error that we should handle
as a success.

no error if we get NOT_FOUND on a state=absent

---

vmware_rest_code_generator/cmd/refresh_modules.py

Avoid errors like those:
```
ERROR: tests/sanity/ignore-2.13.txt:1091:43: Sanity test 'compile-2.6' does not exist
ERROR: tests/sanity/ignore-2.13.txt:1094:43: Sanity test 'import-2.6' does not exist
```

ignores: skip py2.6 tests on 2.13

---

commit_modules.sh

Don't git add CHANGELOG.rst too early.

commit_modules.sh: import CHANGELOG.rst once it's generated

---

commit_modules.sh

tests/output/.tmp presence depends on the Ansible version.

commit_modules.sh: tests/output/.tmp may not exist

---

commit_modules.sh

Call `ansible-test` with `--docker` to avoid a dependency with the local
system.

commit_modules.sh: ansible-test --docker

---

vmware_rest_code_generator/cmd/refresh_modules.py

We don't support yet these async tasks.

ignore end-points where they return a task id

---

setup.cfg

License noted in setup.cfg was different from the actual LICENSE.  Correct the setup.cfg file.
Package has never been published to pypi so should only affect contributors who may have committed while there were different licenses noted.
- Docs Pull Request
setup.cfg
As this could be considered a re-licensing, all contributors with commits during the time period that Apache was listed in setup.cfg will need to ack this PR before merging.

Reconcile license information in setup.cfg with LICENSE

---

commit_modules.sh

The fix is now merged. We can remove the workaround.

commit_modules.sh: drop workaround for collection_prep

---

vmware_rest_code_generator/cmd/refresh_modules.py

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Depends-On: https://github.com/ansible-collections/gouttelette/pull/6
This PR moves few functions from refresh_modules.py to  https://github.com/ansible-collections/gouttelette. These functions will be shared by https://github.com/ansible-collections/amazon_cloud_code_generator.
- Feature Pull Request
```paste below
```

Move functions from refresh_modules.py to shared repo

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py

Follow up to the migration to gouttelette, the documenation block
is now indented with 4 spaces.
Drop `test_filter_out_trusted_module()` since the feature is already
covered at the gouttelette level.

test_gen_documentation: adjustment to be compatible with gouttelette

---

vmware_rest_code_generator/cmd/test_refresh_modules.py

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1727
Merge two duplicated `test_python_type()` tests.

test_python_type: extend the test
