ansible-collections/vmware_rest_code_generator

refresh_modules.py

Prepare the `ignore-2.10.txt` file for `ansible-test`.

generate the ignore_file too

---

README.md

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/8

README: explain how to generate the modules

---

refresh_modules.py
test_refresh_modules.py

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/11
This module depends on vcenter_guest_customization_specs that we don't
generate yet.

do not generate vcenter_vm_guest_customization

---

module_utils/vmware_rest.py
refresh_modules.py
tox.ini

Import the module_utils file in the repository, this way we won't
have to update the two repositories at the same time anymore.

import the module_utils file

---

module_utils/vmware_rest.py
refresh_modules.py
test_refresh_modules.py
tox.ini

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/14
Add a new key called PAYLOAD_FORMAT that describe the format of
the data to send back to the end-points.
This supersedes the previous IN_QUERY_PARAMETER since it also exposes
the format of the data to POST back to the server.

use PAYLOAD_FORMAT to describe final data format

---

module_utils/vmware_rest.py
refresh_modules.py

Use `exists()` to do a lookup and get the id of the device to remove.
Also, only use pci_slot_number as unicity criteria

adapter: do a look up to get the id of the device

---

refresh_modules.py

vm_hardware already expose the same features.

don't generate vm_hardware_action_upgrade

---

module_utils/vmware_rest.py
refresh_modules.py

Found with `vcenter_vm_hardware_boot_device`.

handle the 'set' operation

---

module_utils/vmware_rest.py
refresh_modules.py
test_refresh_modules.py

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/643
- correctly set the element types
- don't set subkeys in the payload data structure, it's not needed

simplify the payload structure managment

---

refresh_modules.py

Show up the Ansible states instead of the VMware OperationIds.

doc: show up the Ansible states

---

module_utils/vmware_rest.py
refresh_modules.py

Add the ability to use the resource "label" to identify a resource.

ability to use the "label" to identify resoure

---

refresh_modules.py

Fix a regression introduced in 71ee926df6f11f0d9b0dabef802124cb071c04c3

fix when list_index is None

---

refresh_modules.py

- add `vcenter_storage_policies`
- add `vcenter_vm_storage_policy_compliance`

adjust what storage module that we build

---

refresh_modules.py
test_refresh_modules.py

- add I() and C() functions
- reformat some autogenerate blocks

doc: more natural wording

---

refresh_modules.py
test_refresh_modules.py

Move all the description reformatting functions in this static class.

add Description class

---

module_utils/vmware_rest.py

Catch the `aiohttp.client_exceptions.ClientConnectorError` and raise
`EmbeddedModuleFailure`.

open_session: properly handle connection error

---

refresh_examples.py

- accept FQCN, instead of just the module name
- read the collection name from the `galalxy.yml` file

refresh_examples: handle FQCN

---

commit_modules.sh

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/49

commit_modules: generate the HTML doc

---

test_refresh_modules.py
tox.ini

This way the CI will run tox for us.

tox: use pyXX env to run the test-suite

---

refresh_examples.py

We can face a case where `depends_on` and `blocks` come with
the same block. We now check unicity before when we flatten everything.

avoid duplicated blocks

---

refresh_examples.py

For instance: `lookup('env', 'ESXI1_HOSTNAME')`

refresh_examples: accept lookup() var

---

refresh_modules.py
requirements.txt

Remove the dependency on astunparse. We don't access Python AST anymore.
See: #38

drop the astunparse dependency

---

refresh_modules.py

This will help to understand how a module was built.
Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/59
Closes: #38

add the names of the templates in the final result

---

refresh_modules.py

Do not ignore the err500 coming from the server.

raise an error in case of status == 500

---

module_utils/vmware_rest.py
refresh_modules.py

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/72
Handle import error with correct exception raised while
importing aiohttp
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
module_utils/vmware_rest.py
refresh_modules.py

Handle import error for aiohttp

---

README.md

Explain step by step how to generate the content of the
`vmware.vwmware_rest` collection.

doc: explain how to refresh vmware_rest content

---

module_utils/test_vmware_rest.py
module_utils/vmware_rest.py
tox.ini

Ensure we also validate the format of the the module_utils directory.

tox: enforce black formatter on module_utils dir

---

refresh_modules.py

Manually set the collection name.
See: https://github.com/ansible-collections/cloud.common/commit/e6640acc6d5151697e4ca677f5be18619b78e69a

turbo mode: set the collection_name manually

---

README.md
refresh_modules.py
test_refresh_modules.py

* Typo fixes
* Documentation update
* Code refactoring
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
- Docs Pull Request

Misc. fixes

---

vmware_rest_code_generator/cmd/refresh_modules.py

Workaround to avoid an exception in `ansible-test`.
See: https://github.com/ansible/ansible/pull/73322

set collection_name outside the try/except block

---

requirements.txt
setup.cfg
vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/templates/default_module.j2
vmware_rest_code_generator/templates/info_list_and_get_module.j2
vmware_rest_code_generator/templates/info_no_list_module.j2

- Move the templates out of `refresh_modules.py`.
- Convert them in Jinj2.

convert the template to Jinja2

---

vmware_rest_code_generator/cmd/refresh_modules.py

- drop `gen_url_func()`, use a template instead
- rename `path()` to `get_path()`

use get_path() to get the base path

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/templates/default_module.j2

This was the last Python-style code template. Now the full content of
the modules is generated from the Jinja2 templates.

jinj2: drop gen_entry_point_func() function

---

vmware_rest_code_generator/cmd/content_library_data.py
vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py
vmware_rest_code_generator/module_utils/vmware_rest.py
vmware_rest_code_generator/templates/default_module.j2
vmware_rest_code_generator/templates/info_list_and_get_module.j2
vmware_rest_code_generator/templates/info_no_list_module.j2

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
See: https://github.com/ansible-collections/vmware.vmware_rest/issues/149
- Bugfix Pull Request
refresh_modules.py

Add support for content library info modules

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/templates/default_module.j2
vmware_rest_code_generator/templates/info_list_and_get_module.j2
vmware_rest_code_generator/templates/info_no_list_module.j2

Clean up the code to simplify the generation of the plugins.

jinja2: simplify the rendering

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py
vmware_rest_code_generator/templates/default_module.j2
vmware_rest_code_generator/templates/info_list_and_get_module.j2
vmware_rest_code_generator/templates/info_no_list_module.j2

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/92
- Handle the subitems
- Deal witha corner-case where the `required` flag was lost
- Set the `required_if` validation structure

improve the management of the required keys

---

README.md

Use a simpler approach to refresh the modules.

doc: explain how to fresh the modules

---

vmware_rest_code_generator/module_utils/vmware_rest.py

The output of the modules is different most of the times since there
is no more `value` key in the answer.

update_changed_flag: refactoring for vSphere 7.0.2

---

vmware_rest_code_generator/module_utils/vmware_rest.py

Some few modules return a JSON structure as text.

update_changed_flag: isolate the text to json conversion

---

vmware_rest_code_generator/cmd/refresh_modules.py

We now need the file to test against Ansible devel.

also generate ignore-2.12.txt

---

vmware_rest_code_generator/cmd/refresh_modules.py

The module returns an err 500.

don't generate appliance_health_system_lastcheck

---

vmware_rest_code_generator/cmd/refresh_examples.py

- follow the natural execution flow
- allow more than one single dependency level

example: better dep handling

---

vmware_rest_code_generator/module_utils/vmware_rest.py

Import a fix from Alina.
See: https://github.com/ansible-collections/vmware.vmware_rest/pull/199

gen_args does not concatenate as as expected.

---

commit_modules.sh

Also drop the docs symlink and pass the right Python version to `ansible-test`.

commit_modules.sh: use vmware_rest's tox

---

requirements.txt
vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py

Automatically set the version_added based on the state of the target git repository.

automatically refresh the version_added field

---

vmware_rest_code_generator/templates/info_list_and_get_module.j2

Drop the try/except block to keep any potential exception
visible.

info_list_and_get_module.j2: avoid the try/except

---

vmware_rest_code_generator/module_utils/vmware_rest.py

The API is a bit special for this one.

workaround for content_library_item_info

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py

- show up all the subkeys
- document which state is associated with the subkey

doc: better managment of the subkeys

---

vmware_rest_code_generator/cmd/content_library_data.py
vmware_rest_code_generator/cmd/refresh_modules.py

Depends-On: https://github.com/ansible-collections/vmware_rest_code_generator/pull/151

doc: improve the name label transformation

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/module_utils/vmware_rest.py
vmware_rest_code_generator/templates/header.j2

session timeout for aiohttp client session
- Feature Pull Request

add session timeout for vmware rest

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/templates/header.j2

rename vcenter_rest_session_timeout to just session_timeout

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/module_utils/vmware_rest.py
vmware_rest_code_generator/templates/default_module.j2
vmware_rest_code_generator/templates/header.j2
vmware_rest_code_generator/templates/info_list_and_get_module.j2
vmware_rest_code_generator/templates/info_no_list_module.j2

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1073
Don't use a global value to set the timeout. This works poorly with the cached session.

implement session_timeout at the module level

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/config/modules.yaml

This reverts commit d48536d3ee64047762c5566e0e0c83d2a842fcff.

Revert "remove vcenter_vm_guest_customization for now"

---

commit_modules.sh

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1201

commit_modules.sh: run the linters

---

vmware_rest_code_generator/config/modules.yaml

They don't work properly with vSphere 7.0.3 and should not be part
of the collection.

remove some broken modules

---

vmware_rest_code_generator/module_utils/vmware_rest.py

See: https://docs.ansible.com/ansible/latest/dev_guide/developing_module_utilities.html#standard-module-utilities

the module_utils file is also BSD licensed

---

vmware_rest_code_generator/config/modules.yaml
vmware_rest_code_generator/module_utils/vmware_rest.py
vmware_rest_code_generator/templates/default_module.j2

These items have to be stored on a Content Library. Also fix the
idempotency of the OVF creation.

add support form VM template items

---

commit_modules.sh

See:
- https://github.com/ansible-collections/vmware.vmware_rest/pull/340
- https://github.com/ansible-collections/vmware.vmware_rest/pull/339

run the new integration tests

---

vmware_rest_code_generator/module_utils/test_vmware_rest.py
vmware_rest_code_generator/module_utils/vmware_rest.py
vmware_rest_code_generator/templates/info_list_and_get_module.j2

See: https://github.com/ansible-collections/vmware.vmware_rest/issues/362

protect the URL parameters

---

requirements.txt
tox.ini

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1715
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1716

tox: add the generate environment

---

vmware_rest_code_generator/cmd/refresh_modules.py

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1715

use jinja2_renderer from gouttelette.utils

---

vmware_rest_code_generator/cmd/refresh_modules.py
vmware_rest_code_generator/cmd/test_refresh_modules.py

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1727
Drop some cases that we don't meet with 7.0.2+ and add test coverage.

simplify path_to_name()
